#==========================================================================
# Description: Rebuild Armbian for TY1608
#==========================================================================

name: Build armbian for TY1608

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      base_image_url:
        description: "Official Armbian base image URL"
        required: false
        default: "https://dl.armbian.com/odroidn2/archive/Armbian_26.5.1_Odroidn2_trixie_current_6.18.33_minimal.img.xz"
        type: string
      armbian_fstype:
        description: "Select armbian rootfs type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs
      armbian_board:
        description: "Select device board."
        required: false
        default: "s905l3b-ip103h"
        type: choice
        options:
          - s905l3b-ip103h
          - s905l3b
          - s905l3b-e900v22d
          - s905l3b-e900v22e
      armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "5.10.1"
        type: choice
        options:
          - 5.10.1
          - 5.15.1
          - 6.1.1
          - 5.4.1_5.10.1
          - 5.15.1_6.1.1
      auto_kernel:
        description: "Auto use the latest kernel."
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository."
        required: false
        default: "ophub/kernel"
        type: choice
        options:
          - ophub/kernel
      kernel_usage:
        description: "Set the kernel line."
        required: false
        default: "stable"
        type: choice
        options:
          - stable
          - flippy
          - dev
          - beta
      armbian_storage:
        description: "Select image storage type."
        required: false
        default: "save"
        type: choice
        options:
          - save
          - temp

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare release tag
        id: prep
        shell: bash
        run: |
          echo "build_tag=Armbian_rebuild_${{ inputs.armbian_storage }}_$(date +'%Y.%m.%d-%H%M')" >> "${GITHUB_OUTPUT}"
          echo "Using base image: ${{ inputs.base_image_url }}"

      - name: Rebuild Armbian
        uses: ophub/amlogic-s9xxx-armbian@main
        with:
          build_target: armbian
          armbian_path: ${{ inputs.base_image_url }}
          armbian_board: ${{ inputs.armbian_board }}
          armbian_kernel: ${{ inputs.armbian_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          kernel_usage: ${{ inputs.kernel_usage }}
          armbian_fstype: ${{ inputs.armbian_fstype }}
          gh_token: ${{ secrets.GH_TOKEN || github.token }}

      - name: Upload Rebuild image to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS == 'success' && !cancelled() }}
        with:
          tag: ${{ steps.prep.outputs.build_tag }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GH_TOKEN || github.token }}
          body: |
            ### Armbian Image information
            - Base image: `${{ inputs.base_image_url }}`
            - Default username: `root`
            - Default password: `1234`
            - Install command: `armbian-install`
            - Update command: `armbian-update`
